extends:
  - standard

plugins:
  - node

parserOptions:
  sourceType: module

rules:
  arrow-parens:
    - warn
    - as-needed
    - requireForBlockBody: false
  new-cap:
    - error
    - newIsCap: true
      capIsNew: true
  no-shadow: warn
  no-return-await: warn
  no-unused-expressions: off
  no-var: warn
  prefer-const: warn
  strict:
    - warn
    - never

  import/newline-after-import: warn
  import/no-absolute-path: warn
  import/no-dynamic-require: warn
  import/no-extraneous-dependencies: warn
  import/no-mutable-exports: warn
  import/order:
    - warn
    - groups:
        - - builtin
          - external
        - - sibling
          - index
        - parent
      newlines-between: always-and-inside-groups

  node/exports-style: warn
  node/no-unsupported-features/es-builtins: warn
  node/no-unsupported-features/es-syntax:
    - warn
    - ignores:
        - modules
        - dynamicImport
  node/no-unsupported-features/node-builtins: warn
  node/shebang: warn

  promise/catch-or-return:
    - warn
    - terminationMethod:
        - catch
        - asCallback
  promise/no-callback-in-promise: warn
  promise/no-return-wrap: warn

overrides:
  - files:
      - tests/**/*.mjs

    extends:
      - plugin:mocha/recommended

    plugins:
      - chai-expect
      - chai-friendly
      - mocha

    env:
      mocha: true

    globals:
      expect: true
      mockImport: true
      sinon: true

    rules:
      chai-expect/no-inner-compare: error
      chai-expect/missing-assertion: error
      chai-expect/terminating-properties: error

      chai-friendly/no-unused-expressions: error

      import/no-extraneous-dependencies:
        - warn
        - devDependencies: true

      mocha/prefer-arrow-callback: warn


