name: CI

on:
  push:
    branches: '*'
    tags: '*'

  workflow_dispatch:

env:
  root_file: <%= root_file %>

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    steps:
      - name: Install pdf-info
        run: |
          apt-get update && apt-get install poppler-utils -y

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Document
        run: |
          <%_ if (locals.hasBiblography) { _%>
          pdflatex -interaction=nonstopmode -jobname=output -shell-escape ${{ env.root_file }}
          bibtex output.aux
          <%_ } _%>
          pdflatex -interaction=nonstopmode -jobname=output -shell-escape ${{ env.root_file }}
          pdflatex -interaction=nonstopmode -jobname=output -shell-escape ${{ env.root_file }}

      - name: Rename Document
        id: rename_doc
        run: |
          MAIN_DOC_NAME=$(pdfinfo output.pdf | grep -ia --color=none -e '^title:\s*' | tail -c +7 | awk '{$1=$1};1' | tr ' ' '_')
          if [ -z $MAIN_DOC_NAME ]; then
            MAIN_DOC=output.pdf
            echo "No pdf properties, renaming skipped."
          else
            MAIN_DOC=$MAIN_DOC_NAME.pdf
            echo "Renaming document to $MAIN_DOC..."
            cp output.pdf "$MAIN_DOC"
            echo "Renaming complete."
          fi
          echo "main_doc=$MAIN_DOC" >> $GITHUB_OUTPUT

      - name: Upload Document
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.gcredentials }}
          filename: ${{ steps.rename_doc.outputs.main_doc }}
          folderId: ${{ secrets.drive_folder }}
          name: ${{ github.event.repository.name }}.${{ github.ref_name }}.pdf
          overwrite: true

      - name: Collect sources
        id: collect_src
        if: github.ref_type == 'tag'
        run: |
          zip ${{ github.event.repository.name }}_src.zip *.tex *.bbl *.ind *.gls *.nls

      - name: Release Document
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ steps.rename_doc.outputs.main_doc }}
            ${{ github.event.repository.name }}_src.zip